controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  
# yearbook_home:
#   path: "/"
#   controller: 'App\Controller\YearbookController::index'

# app_login:
#   path: "/login"
#   controller: 'App\Controller\SecurityController::login'

# app_register:
#   path: "/register"
#   controller: 'App\Controller\SecurityController::register'

# app_logout:
#   path: "/logout"
#   controller: 'App\Controller\SecurityController::logout'
